@baseUrl = http://localhost:3000/auth

# @name successLogin
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "christian.dejesus@usc.edu.ph",
  "password": "christianDeJesus1"
}

# Expected:
#
# {
#   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjaHJpc3RpYW4uZGVqZXN1c0B1c2MuZWR1LnBoIiwicm9sZXMiOlsiQ0lTQ09fQURNSU4iXSwiaWF0IjoxNjk4NzYwMTU5LCJleHAiOjE2OTkzNjQ5NTl9.e7R-SBBauvZnAJIMA0WA25brT2roLowmIclRbmfv860",
#   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjaHJpc3RpYW4uZGVqZXN1c0B1c2MuZWR1LnBoIiwicm9sZXMiOlsiQ0lTQ09fQURNSU4iXSwiaWF0IjoxNjk4NzYwMTU5LCJleHAiOjE2OTkzNjQ5NTl9.2BO6zXxHq6wnV4ItD90Gy_T9g6uN4qdsdxvcZ1zZVgE"
# }

###
# @name nonExistentEmail
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "i-dont-exist@gmail.com",
  "password": "test12345"
}

# Expected:
#
# {
#   "errors": [
#     {
#       "msg": "Your email or password is incorrect"
#     }
#   ]
# }

###
# @name wrongPassword
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "christian.dejesus@usc.edu.ph",
  "password": "wrongpassword123"
}

# Expected:
#
# {
#   "errors": [
#     {
#       "msg": "Your email or password is incorrect"
#     }
#   ]
# }