@baseUrl = http://localhost:3000/document
@documentId = 3

# @name byOwner
POST {{baseUrl}}/{{documentId}}/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJub3JtYWwuc3R1ZGVudEB1c2MuZWR1LnBoIiwicm9sZXMiOlsiU1RVREVOVCJdLCJpYXQiOjE2OTg3NjMxNzUsImV4cCI6MTY5OTM2Nzk3NX0.jKrmLRPUsUKexwMpLpCXNqBDFPlTExHfEhurNBkTmdM

{
  "content": "test comment by normal.student@usc.edu.ph - STUDENT role and OWNER"
}

###
# @name byCiscoAdmin
# you need to give the user the CISCO_ADMIN role in the UserRole table first
POST {{baseUrl}}/{{documentId}}/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjaHJpc3RpYW4uZGVqZXN1c0B1c2MuZWR1LnBoIiwicm9sZXMiOlsiQ0lTQ09fQURNSU4iXSwiaWF0IjoxNjk4NzYwMTU5LCJleHAiOjE2OTkzNjQ5NTl9.e7R-SBBauvZnAJIMA0WA25brT2roLowmIclRbmfv860

{
  "content": "test comment by christian.dejesus@usc.edu.ph - with CISCO_ADMIN role"
}

###
# @name byCiscoMember
# you need to give the user the CISCO_MEMBER role in the UserRole table first
POST {{baseUrl}}/{{documentId}}/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJjaXNjby5tZW1iZXJAdXNjLmVkdS5waCIsInJvbGVzIjpbIkNJU0NPX01FTUJFUiJdLCJpYXQiOjE2OTg3NjMyNDQsImV4cCI6MTY5OTM2ODA0NH0.HZNPZ4txdEBQQDPg_mLMHkCpY7gl_yuD6EIKfwNJbts

{
  "content": "test comment by cisco.member@usc.edu.ph - with CISCO_MEMBER role"
}

###
# @name byNotRelevant
# another STUDENT without any EDIT permissions
POST {{baseUrl}}/{{documentId}}/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJhbm90aGVyLnN0dWRlbnRAdXNjLmVkdS5waCIsInJvbGVzIjpbIlNUVURFTlQiXSwiaWF0IjoxNjk4NzYzMjE5LCJleHAiOjE2OTkzNjgwMTl9.GZzPVLWuYFs-Z2DLEtnRuT6QJ__1kkz9deriqnil2BI

{
  "content": "test comment by another.student@usc.edu.ph - with STUDENT ROLE AND NO EDIT"
}