@baseUrl = http://localhost:3000/user

###
# @name registerUser
POST {{baseUrl}}/
Content-Type: application/json

{
  "email": "new.student@gmail.com",
  "password1": "new12345",
  "password2": "new12345"
}

# Expected: status code 200 OK on successful unique membership register, otherwise:
#
# {
#   "errors": [
#     {
#       "type": "field",
#       "value": "newstudent@gmail.com",
#       "msg": "User with that email already exists.",
#       "path": "email",
#       "location": "body"
#     }
#   ]
# }